/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;

import com.mycompany.ui.model.Appointment;
import com.mycompany.ui.model.AppointmentTableModel;
import com.mycompany.model.*;
import com.mycompany.ui.components.*;
import java.util.Arrays;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Main application frame for the Smart Medical Manager.
 * Follows MVC pattern with separated concerns.
 * Observes Model changes and updates View accordingly.
 *
 * @author Ji
 */
public class MainFrame extends javax.swing.JFrame implements FeatureObserver, PatientObserver, AppointmentObserver {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    private AppointmentTableModel appointmentModel;
    private AppointmentManager appointmentManager;
    private FeatureManager featureManager;
    private PatientManager patientManager;
    private DataProvider dataProvider;
    private TimePickerPanel timePicker;
    private boolean showUpcomingOnHome = true; // Toggle for home page appointments
    private Appointment appointmentBeingModified = null; // Track which appointment is being edited

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        // Initialize Model managers
        this.appointmentManager = AppointmentManager.getInstance();
        this.featureManager = FeatureManager.getInstance();
        this.patientManager = PatientManager.getInstance();
        this.dataProvider = DataProvider.getInstance();
        
        // Register as observer for model changes
        appointmentManager.registerObserver(this);
        featureManager.registerObserver(this);
        patientManager.registerObserver(this);
        
        // Initialize UI with data
        initializeUI();
    }
    
    /**
     * Initialize UI with data from Model layer.
     * Separates data loading from UI generation.
     */
    private void initializeUI() {
        initializeAppointmentData();
        setupSearchFunctionality();
        populateDropdowns();
        initializeTimePicker();
        updateProfileDisplay();
        initializeFeatureCheckboxes();
        updateHomePageAppointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mainTabs = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        upcomingAppointments = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        date1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        date2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        date3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        notificationsRemindersList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        toggleAppointmentsBtn = new javax.swing.JButton();
        appointmentsTab = new javax.swing.JPanel();
        appointmentsView = new javax.swing.JPanel();
        appointmentsTableScroll = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        newBtn = new javax.swing.JButton();
        filterLabel = new javax.swing.JLabel();
        appointmentOpsLabel = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        modifyBtn = new javax.swing.JButton();
        cancelAppBtn = new javax.swing.JButton();
        applyFilterBtn = new javax.swing.JButton();
        timePeriodList = new javax.swing.JList<>();
        filterSeparator = new javax.swing.JSeparator();
        bookPanel = new javax.swing.JPanel();
        consultationType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        location = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        personnel = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        roomType = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JCalendar();
        bookBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        profileTab = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        settingsTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        featurePanel = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        adminTab = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Notifications & Reminders");

        jPanel2.setLayout(new java.awt.GridLayout(0, 2));

        date1.setText("");
        jPanel2.add(date1);

        jButton1.setText("View Details");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);

        date2.setText("");
        jPanel2.add(date2);

        jButton2.setText("View Details");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel2.add(jButton2);

        date3.setText("");
        jPanel2.add(date3);

        jButton3.setText("View Details");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3);

        upcomingAppointments.setViewportView(jPanel2);

        notificationsRemindersList.setViewportView(jList1);

        jLabel6.setText("Upcoming appointment(s)");
        jLabel6.setFont(new java.awt.Font("Dialog", java.awt.Font.BOLD, 14));

        toggleAppointmentsBtn.setText("Show Past Appointments");
        toggleAppointmentsBtn.addActionListener(e -> toggleHomePageAppointments());

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upcomingAppointments)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addComponent(notificationsRemindersList)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleAppointmentsBtn)))
                .addContainerGap())
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleAppointmentsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upcomingAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificationsRemindersList, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabs.addTab("Home", homeTab);

        appointmentsTab.setLayout(new java.awt.CardLayout());

        // Table model will be set in initializeAppointmentData()
        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel());
        appointmentsTable.setColumnSelectionAllowed(true);
        appointmentsTableScroll.setViewportView(appointmentsTable);
        appointmentsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (appointmentsTable.getColumnModel().getColumnCount() > 0) {
            appointmentsTable.getColumnModel().getColumn(0).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(1).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(2).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(3).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        newBtn.setText("New Appointment");
        newBtn.addActionListener(this::newBtnActionPerformed);

    filterLabel.setText("Search & Filters");

        appointmentOpsLabel.setText("Appointment Operations");

        searchBar.setText("Search...");
        searchBar.setToolTipText("");
        searchBar.addActionListener(this::searchBarActionPerformed);

        modifyBtn.setText("Modify Appointment");
        modifyBtn.addActionListener(this::modifyBtnActionPerformed);

        cancelAppBtn.setText("Cancel Appointment");
        cancelAppBtn.addActionListener(this::cancelAppBtnActionPerformed);

        applyFilterBtn.setText("Apply Filter");
        applyFilterBtn.addActionListener(this::applyFilterBtnActionPerformed);

        timePeriodList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Today", "This Week", "All Upcoming", "Past Appointments" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        filterSeparator.setOrientation(javax.swing.SwingConstants.HORIZONTAL);

        javax.swing.GroupLayout appointmentsViewLayout = new javax.swing.GroupLayout(appointmentsView);
        appointmentsView.setLayout(appointmentsViewLayout);
        appointmentsViewLayout.setHorizontalGroup(
            appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(applyFilterBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filterSeparator)
                    .addComponent(searchBar)
                    .addComponent(cancelAppBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appointmentOpsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(appointmentsViewLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(timePeriodList, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(appointmentsTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        appointmentsViewLayout.setVerticalGroup(
            appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsViewLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentsTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(appointmentsViewLayout.createSequentialGroup()
                        .addComponent(filterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timePeriodList, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(applyFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(appointmentOpsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelAppBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        appointmentsTab.add(appointmentsView, "card6");

        consultationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surgery", "Dentist", "Type1", "Type2", "Type3" }));
        consultationType.addActionListener(this::consultationTypeActionPerformed);

        jLabel7.setText("Consultation Type");

        jLabel8.setText("Location");

        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital 1", "Hospital 2", "Hospital 3" }));
        location.addActionListener(this::locationActionPerformed);

        jLabel9.setText("Personnel");

        personnel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor A", "Doctor B", "Doctor C" }));
        personnel.addActionListener(this::personnelActionPerformed);

        jLabel10.setText("Room Type");

        roomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shared", "Private" }));
        roomType.addActionListener(this::roomTypeActionPerformed);

        bookBtn.setText("Book");
        bookBtn.addActionListener(this::bookBtnActionPerformed);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultationType, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personnel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(consultationType)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(location)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(personnel)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(roomType)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        appointmentsTab.add(bookPanel, "card3");

        mainTabs.addTab("Appointments", appointmentsTab);

        jLabel12.setText("First Name : Abcdefg");

        jLabel13.setText("Last Name : Hijklmnop");

        jLabel14.setText("Sex : M");

        jLabel15.setText("Age : 31");

        jLabel16.setText("Ect : ...");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(0, 511, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel11.setText("Profile Image");

        jButton6.setText("Request Attestation");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Modify Billing");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel18.setText("Billing Information");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(533, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(405, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout profileTabLayout = new javax.swing.GroupLayout(profileTab);
        profileTab.setLayout(profileTabLayout);
        profileTabLayout.setHorizontalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileTabLayout.setVerticalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(profileTabLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabs.addTab("Profile", profileTab);

        featurePanel.setLayout(new java.awt.GridLayout(0, 1));

        jCheckBox5.setText("jCheckBox5");
        featurePanel.add(jCheckBox5);

        jCheckBox4.setText("jCheckBox4");
        featurePanel.add(jCheckBox4);

        jCheckBox1.setText("jCheckBox1");
        featurePanel.add(jCheckBox1);

        jCheckBox6.setText("jCheckBox6");
        featurePanel.add(jCheckBox6);

        jCheckBox3.setText("jCheckBox3");
        featurePanel.add(jCheckBox3);

        jScrollPane1.setViewportView(featurePanel);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel1.setText("Theme");

        jLabel3.setText("Option2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Option3");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Option4");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Option5");

        javax.swing.GroupLayout settingsTabLayout = new javax.swing.GroupLayout(settingsTab);
        settingsTab.setLayout(settingsTabLayout);
        settingsTabLayout.setHorizontalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        settingsTabLayout.setVerticalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox5)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 566, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mainTabs.addTab("Settings", settingsTab);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("OptionName");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton4.setActionCommand("addOption");
        jButton4.setLabel("Add Option");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultation Type", "Location", "Staff", "Room Type" }));
        jComboBox6.setAutoscrolls(true);
        jComboBox6.setRequestFocusEnabled(false);

        jLabel19.setText("Time Event System");

        javax.swing.GroupLayout adminTabLayout = new javax.swing.GroupLayout(adminTab);
        adminTab.setLayout(adminTabLayout);
        adminTabLayout.setHorizontalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        adminTabLayout.setVerticalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        mainTabs.addTab("Admin", adminTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainTabs.getAccessibleContext().setAccessibleName("mainTabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        performSearch();
    }//GEN-LAST:event_searchBarActionPerformed
    
    /**
     * Initializes appointment data from the Model layer.
     * Replaces hardcoded sample data with data from AppointmentManager.
     */
    private void initializeAppointmentData() {
        appointmentModel = new AppointmentTableModel();
        
        // Load all appointments from manager
        for (Appointment appointment : appointmentManager.getAllAppointments()) {
            appointmentModel.addAppointment(appointment);
        }
        
        // Set the model to the table
        appointmentsTable.setModel(appointmentModel);
    }
    
    /**
     * Setup search functionality with real-time filtering.
     * Delegates filtering logic to the model layer.
     */
    private void setupSearchFunctionality() {
        // Add document listener for real-time search as user types
        searchBar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                performSearch();
            }
            
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                performSearch();
            }
            
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                performSearch();
            }
        });
        
        // Clear placeholder text on focus
        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if ("Search...".equals(searchBar.getText())) {
                    searchBar.setText("");
                }
            }
            
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (searchBar.getText().isEmpty()) {
                    searchBar.setText("Search...");
                }
            }
        });
    }
    
    /**
     * Performs search by delegating to the model.
     * UI layer only handles getting the search text.
     */
    private void performSearch() {
        String searchText = searchBar.getText().trim();
        
        // Don't filter on the placeholder text
        if ("Search...".equals(searchText)) {
            appointmentModel.clearFilter();
        } else {
            appointmentModel.applyFilter(searchText);
        }
    }
    
    /**
     * Populates dropdown menus with data from DataProvider.
     * Replaces hardcoded options throughout the UI.
     */
    private void populateDropdowns() {
        consultationType.setModel(new javax.swing.DefaultComboBoxModel<>(
            dataProvider.getOptionsArray("consultationTypes")
        ));
        location.setModel(new javax.swing.DefaultComboBoxModel<>(
            dataProvider.getOptionsArray("locations")
        ));
        personnel.setModel(new javax.swing.DefaultComboBoxModel<>(
            dataProvider.getOptionsArray("personnel")
        ));
        roomType.setModel(new javax.swing.DefaultComboBoxModel<>(
            dataProvider.getOptionsArray("roomTypes")
        ));
    }
    
    /**
     * Initialize time picker for appointment scheduling.
     */
    private void initializeTimePicker() {
        timePicker = new TimePickerPanel();
        
        // Fix calendar display issue - ensure font is set properly
        try {
            date.setFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12));
            // Force calendar to redraw with proper font
            java.awt.Component[] components = date.getComponents();
            for (java.awt.Component comp : components) {
                if (comp instanceof javax.swing.JPanel) {
                    comp.setFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12));
                }
            }
        } catch (Exception e) {
            logger.warning("Could not fix calendar font: " + e.getMessage());
        }
        
        // Add time picker to booking panel below the calendar
        // Use BorderLayout to position it properly
        javax.swing.JPanel rightPanel = new javax.swing.JPanel();
        rightPanel.setLayout(new java.awt.BorderLayout(5, 5));
        rightPanel.add(date, java.awt.BorderLayout.NORTH);
        
        javax.swing.JPanel timePanel = new javax.swing.JPanel();
        timePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Time"));
        timePanel.add(timePicker);
        rightPanel.add(timePanel, java.awt.BorderLayout.CENTER);
        
        // Replace calendar in bookPanel with our new panel containing both calendar and time picker
        // This requires modifying the layout, so we rebuild the right side
        bookPanel.removeAll();
        rebuildBookingPanel(rightPanel);
    }
    
    /**
     * Rebuilds booking panel with time picker integrated.
     */
    private void rebuildBookingPanel(javax.swing.JPanel rightPanel) {
        bookPanel.setLayout(new java.awt.BorderLayout(10, 10));
        
        // Left side with form fields
        javax.swing.JPanel leftPanel = new javax.swing.JPanel();
        leftPanel.setLayout(new java.awt.GridLayout(5, 2, 5, 5));
        leftPanel.add(jLabel7);
        leftPanel.add(consultationType);
        leftPanel.add(jLabel8);
        leftPanel.add(location);
        leftPanel.add(jLabel9);
        leftPanel.add(personnel);
        leftPanel.add(jLabel10);
        leftPanel.add(roomType);
        
        // Button panel at bottom
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));
        buttonPanel.add(cancelBtn);
        buttonPanel.add(bookBtn);
        
        // Add all to bookPanel
        bookPanel.add(leftPanel, java.awt.BorderLayout.WEST);
        bookPanel.add(rightPanel, java.awt.BorderLayout.CENTER);
        bookPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);
        
        bookPanel.revalidate();
        bookPanel.repaint();
    }
    
    /**
     * Updates profile display with current patient information.
     * Gets data from PatientManager instead of hardcoded placeholders.
     */
    private void updateProfileDisplay() {
        PatientManager.Patient patient = patientManager.getCurrentPatient();
        jLabel12.setText("First Name : " + patient.getFirstName());
        jLabel13.setText("Last Name : " + patient.getLastName());
        jLabel14.setText("Sex : " + patient.getSex());
        jLabel15.setText("Age : " + patient.getAge());
        jLabel16.setText("Insurance : " + patient.getInsuranceLevel());
        jTextArea1.setText("Current Medication: " + patient.getCurrentMedication() + "\n" +
                          "Vaccines: " + patient.getVaccines());
    }
    
    /**
     * Updates home page with upcoming or past appointments dynamically.
     */
    private void updateHomePageAppointments() {
        try {
            java.util.List<Appointment> appointments = showUpcomingOnHome ?
                appointmentManager.getUpcomingAppointments() :
                appointmentManager.getPastAppointments();

            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy");

            // Update header and toggle button
            jLabel6.setText(showUpcomingOnHome ? "Upcoming Appointments" : "Past Appointments");
            if (toggleAppointmentsBtn != null) {
                toggleAppointmentsBtn.setText(showUpcomingOnHome ? "Show Past Appointments" : "Show Upcoming Appointments");
            }

            // Clear dynamic list and rebuild to auto-scale
            jPanel2.removeAll();

            if (appointments.isEmpty()) {
                String emptyMessage = showUpcomingOnHome ?
                    "No upcoming appointments scheduled" :
                    "No past appointments found";
                javax.swing.JLabel emptyLabel = new javax.swing.JLabel(emptyMessage);
                jPanel2.add(emptyLabel);
                // Hide notifications for past view
                jLabel2.setVisible(showUpcomingOnHome);
                notificationsRemindersList.setVisible(showUpcomingOnHome);
                if (showUpcomingOnHome) {
                    jList1.setListData(new String[]{emptyMessage});
                } else {
                    jList1.setListData(new String[0]);
                }
            } else {
                // Build rows: [Label][View Details]
                for (Appointment apt : appointments) {
                    try {
                        java.time.LocalDate aptDate = java.time.LocalDate.parse(apt.getDate(), formatter);
                        java.time.DayOfWeek dayOfWeek = aptDate.getDayOfWeek();
                        String dayName = dayOfWeek.toString().substring(0, 1).toUpperCase() +
                                dayOfWeek.toString().substring(1).toLowerCase();
                        String display = dayName + " " + apt.getDate() +
                                " at " + apt.getTime() + " with " + apt.getDoctor();

                        javax.swing.JLabel lbl = new javax.swing.JLabel(display);
                        javax.swing.JButton viewBtn = new javax.swing.JButton("View Details");
                        viewBtn.addActionListener(ev -> {
                            mainTabs.setSelectedIndex(1); // Go to Appointments tab
                            logger.info("Navigated to Appointments tab from home page");
                        });
                        jPanel2.add(lbl);
                        jPanel2.add(viewBtn);
                    } catch (Exception e) {
                        // Fallback label if date parsing fails
                        javax.swing.JLabel lbl = new javax.swing.JLabel(apt.getDate() + " at " + apt.getTime() + " with " + apt.getDoctor());
                        javax.swing.JButton viewBtn = new javax.swing.JButton("View Details");
                        viewBtn.addActionListener(ev -> {
                            mainTabs.setSelectedIndex(1);
                            logger.info("Navigated to Appointments tab from home page");
                        });
                        jPanel2.add(lbl);
                        jPanel2.add(viewBtn);
                    }
                }

                // Notifications show only for upcoming
                jLabel2.setVisible(showUpcomingOnHome);
                notificationsRemindersList.setVisible(showUpcomingOnHome);
                if (showUpcomingOnHome) {
                    java.util.List<String> notifications = new java.util.ArrayList<>();
                    for (Appointment apt : appointments) {
                        notifications.add(apt.getDoctor() + " - " + apt.getDate() + " at " + apt.getTime());
                    }
                    jList1.setListData(notifications.toArray(new String[0]));
                } else {
                    jList1.setListData(new String[0]);
                }
            }

            // Refresh the panel
            jPanel2.revalidate();
            jPanel2.repaint();
        } catch (Exception e) {
            logger.severe("Error updating home page: " + e.getMessage());
        }
    }
    
    /**
     * Toggles between showing upcoming and past appointments on home page.
     */
    private void toggleHomePageAppointments() {
        showUpcomingOnHome = !showUpcomingOnHome;
        updateHomePageAppointments();
        logger.info("Toggled to show " + (showUpcomingOnHome ? "upcoming" : "past") + " appointments");
    }
    
    /**
     * Initializes feature checkboxes with real feature names and listeners.
     * Only shows Reminders and PatientView. Hides Email, AdvancedSearch, and Fast.
     */
    private void initializeFeatureCheckboxes() {
        java.util.List<javax.swing.JCheckBox> checkboxes = Arrays.asList(
            jCheckBox1, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6
        );
        
        java.util.List<String> featureNames = Arrays.asList(
            "Reminders", "AdvancedSearch", "Fast", "PatientView", "Email"
        );
        
        // Features to show: indices 0 (Reminders) and 3 (PatientView)
        java.util.List<Integer> featuresToShow = Arrays.asList(0, 3);
        // Features to hide: indices 1 (AdvancedSearch), 2 (Fast), 4 (Email)
        java.util.List<Integer> featuresToHide = Arrays.asList(1, 2, 4);
        
        // Hide and disable unwanted checkboxes
        for (Integer idx : featuresToHide) {
            checkboxes.get(idx).setVisible(false);
            checkboxes.get(idx).setEnabled(false);
        }
        
        // Setup visible features
        for (Integer featureIdx : featuresToShow) {
            javax.swing.JCheckBox checkbox = checkboxes.get(featureIdx);
            String feature = featureNames.get(featureIdx);
            
            // Set proper label
            checkbox.setText(feature);
            checkbox.setVisible(true);
            checkbox.setEnabled(true);
            
            // Set initial state
            checkbox.setSelected(featureManager.isFeatureActive(feature));
            
            // Add listener for feature activation/deactivation
            checkbox.addActionListener(e -> handleFeatureToggle(feature, checkbox.isSelected(), checkbox));
        }
    }
    
    /**
     * Handles feature activation/deactivation when checkbox is toggled.
     * Special handling for Reminders to show/hide notification preferences.
     */
    private void handleFeatureToggle(String feature, boolean activate, javax.swing.JCheckBox checkbox) {
        try {
            if (activate) {
                featureManager.activateFeatures(feature);
                logger.info("Feature activated: " + feature);
                
                // Special handling for Reminders
                if ("Reminders".equals(feature)) {
                    showReminderOptions();
                }
            } else {
                featureManager.deactivateFeatures(feature);
                logger.info("Feature deactivated: " + feature);
                
                // Special handling for Reminders
                if ("Reminders".equals(feature)) {
                    hideReminderNotifications();
                }
            }
        } catch (IllegalStateException e) {
            // Cannot deactivate mandatory feature
            logger.warning("Cannot deactivate mandatory feature: " + feature);
            checkbox.setSelected(true); // Revert checkbox
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cannot deactivate mandatory feature: " + feature);
        }
    }
    
    /**
     * Shows reminder options when Reminders feature is enabled.
     */
    private void showReminderOptions() {
        String[] options = {"In App", "Email", "Cancel"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this,
            "How would you like to receive appointment reminders?",
            "Reminder Preferences",
            javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);
        
        if (choice == 0) {
            // In App reminders
            featureManager.setFeatureAttribute("Reminders", "type", "InApp");
            logger.info("Reminders set to: In App");
        } else if (choice == 1) {
            // Email reminders - ask for email
            String email = javax.swing.JOptionPane.showInputDialog(this,
                "Enter your email address for appointment reminders:",
                "Email Reminders",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
            
            if (email != null && !email.trim().isEmpty()) {
                if (isValidEmail(email)) {
                    featureManager.setFeatureAttribute("Reminders", "type", "Email");
                    featureManager.setFeatureAttribute("Reminders", "email", email);
                    logger.info("Reminders set to: Email (" + email + ")");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Invalid email format. Please enter a valid email.",
                        "Invalid Email",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    
    /**
     * Hides reminder notifications when Reminders feature is disabled.
     */
    private void hideReminderNotifications() {
        // Hide reminders from home page notifications list
        updateHomePageAppointments();
    }
    
    /**
     * Simple email validation.
     */
    private boolean isValidEmail(String email) {
        return email.matches("^[A-Za-z0-9+_.-]+@(.+)$");
    }

    private void consultationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationTypeActionPerformed
        String selected = (String) consultationType.getSelectedItem();
        logger.info("Consultation type selected: " + selected);
    }//GEN-LAST:event_consultationTypeActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        String selected = (String) location.getSelectedItem();
        logger.info("Location selected: " + selected);
    }//GEN-LAST:event_locationActionPerformed

    private void personnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personnelActionPerformed
        String selected = (String) personnel.getSelectedItem();
        logger.info("Personnel selected: " + selected);
    }//GEN-LAST:event_personnelActionPerformed

    private void roomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeActionPerformed
        String selected = (String) roomType.getSelectedItem();
        logger.info("Room type selected: " + selected);
    }//GEN-LAST:event_roomTypeActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        try {
            String consultType = (String) consultationType.getSelectedItem();
            String loc = (String) location.getSelectedItem();
            String doctor = (String) personnel.getSelectedItem();
            String roomTypeSelected = (String) roomType.getSelectedItem();
            
            // Get date from calendar in dd-MM-yyyy format
            java.util.Date selectedDate = date.getDate();
            if (selectedDate == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a date.");
                return;
            }
            String dateStr = new java.text.SimpleDateFormat("dd-MM-yyyy").format(selectedDate);
            
            // Get time from time picker if available, otherwise default to 09:00
            String timeStr = "09:00";
            if (timePicker != null) {
                timeStr = timePicker.getSelectedTime();
            }
            
            if (appointmentBeingModified != null) {
                // UPDATE MODE: Modify existing appointment
                appointmentBeingModified.setDate(dateStr);
                appointmentBeingModified.setTime(timeStr);
                appointmentBeingModified.setLocation(loc);
                appointmentBeingModified.setDoctor(doctor);
                appointmentBeingModified.setReason(consultType);
                appointmentBeingModified.setAttribute("roomType", roomTypeSelected);
                
                appointmentManager.updateAppointment(appointmentBeingModified);
                
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Appointment updated successfully!\n" + dateStr + " at " + timeStr + " with " + doctor);
                
                logger.info("Appointment updated: " + dateStr + " at " + timeStr + " with " + doctor);
                
                // Reset the modify flag
                appointmentBeingModified = null;
                bookBtn.setText("Book");
            } else {
                // CREATE MODE: New appointment
                Appointment newAppointment = new Appointment(
                    dateStr, timeStr, doctor, loc, consultType, "Scheduled",
                    java.util.Map.of(
                        "consultationType", consultType,
                        "roomType", roomTypeSelected
                    )
                );
                
                appointmentManager.addAppointment(newAppointment);
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Appointment booked successfully!\n" + dateStr + " at " + timeStr + " with " + doctor);
                
                logger.info("Appointment booked: " + dateStr + " at " + timeStr + " with " + doctor);
            }
            
            // Auto-return to appointments view after successful booking/update
            // Use CardLayout to switch back to appointmentsView
            java.awt.CardLayout cl = (java.awt.CardLayout) appointmentsTab.getLayout();
            cl.show(appointmentsTab, "card6");  // card6 is the appointmentsView card
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error booking appointment: " + e.getMessage());
            logger.severe("Error booking appointment: " + e.getMessage());
        }
    }//GEN-LAST:event_bookBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Attestation request submitted.");
        logger.info("Attestation request submitted");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // Reset the form for a new appointment
        appointmentBeingModified = null;
        bookBtn.setText("Book");
        
        // Clear form fields
        consultationType.setSelectedIndex(0);
        location.setSelectedIndex(0);
        personnel.setSelectedIndex(0);
        roomType.setSelectedIndex(0);
        date.setDate(new java.util.Date()); // Set to today
        if (timePicker != null) {
            timePicker.setSelectedTime("09:00"); // Default time
        }
        
        // Show the book panel using CardLayout
        java.awt.CardLayout cl = (java.awt.CardLayout) appointmentsTab.getLayout();
        cl.show(appointmentsTab, "card3");  // card3 is the bookPanel card
        logger.info("New appointment form opened");
    }//GEN-LAST:event_newBtnActionPerformed

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        int selectedRow = appointmentsTable.getSelectedRow();
        if (selectedRow >= 0) {
            Appointment selected = appointmentModel.getAppointmentAt(selectedRow);

            // If appointment is cancelled, confirm rescheduling
            if ("Cancelled".equalsIgnoreCase(selected.getStatus())) {
                int choice = javax.swing.JOptionPane.showConfirmDialog(this,
                    "This appointment is cancelled. Do you want to reschedule it?",
                    "Reschedule cancelled appointment",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                if (choice != javax.swing.JOptionPane.YES_OPTION) {
                    return;
                }
                selected.setStatus("Scheduled");
                appointmentManager.updateAppointment(selected);
            }

            appointmentBeingModified = selected; // Track which appointment is being modified
            
            // Pre-fill the booking form with current appointment details
            try {
                // Set all form fields to the appointment's current values
                consultationType.setSelectedItem(selected.getAttribute("consultationType") != null ? 
                    selected.getAttribute("consultationType") : "General Consultation");
                
                location.setSelectedItem(selected.getLocation());
                personnel.setSelectedItem(selected.getDoctor());
                
                // Scroll to date in calendar
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy");
                java.time.LocalDate aptDate = java.time.LocalDate.parse(selected.getDate(), formatter);
                java.util.Calendar cal = java.util.Calendar.getInstance();
                cal.set(aptDate.getYear(), aptDate.getMonthValue() - 1, aptDate.getDayOfMonth());
                date.setDate(cal.getTime());
                
                // Set time in time picker
                if (timePicker != null) {
                    timePicker.setSelectedTime(selected.getTime());
                }
                
                // Change button text and navigate to booking form
                bookBtn.setText("Update Appointment");
                mainTabs.setSelectedIndex(1); // Navigate to Appointments tab
                java.awt.CardLayout cl = (java.awt.CardLayout) appointmentsTab.getLayout();
                cl.show(appointmentsTab, "card3");  // Show booking panel
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Modify the appointment details and click 'Update Appointment' to save changes.",
                    "Modify Appointment",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                logger.info("Loaded appointment for modification: " + selected.getDate());
            } catch (Exception e) {
                logger.severe("Error loading appointment for modification: " + e.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error loading appointment: " + e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment to modify.");
        }
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void cancelAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAppBtnActionPerformed
        int selectedRow = appointmentsTable.getSelectedRow();
        if (selectedRow >= 0) {
            Appointment selected = appointmentModel.getAppointmentAt(selectedRow);
            int option = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Cancel appointment: " + selected.getDate() + " with " + selected.getDoctor() + "?");
            if (option == javax.swing.JOptionPane.YES_OPTION) {
                appointmentManager.cancelAppointment(selected);
                javax.swing.JOptionPane.showMessageDialog(this, "Appointment cancelled successfully.");
                logger.info("Appointment cancelled");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment to cancel.");
        }
    }//GEN-LAST:event_cancelAppBtnActionPerformed

    private void applyFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFilterBtnActionPerformed
        int selectedIndex = timePeriodList.getSelectedIndex();
        if (selectedIndex >= 0) {
            String selected = timePeriodList.getModel().getElementAt(selectedIndex);
            applyDateFilter(selected);
            logger.info("Filter applied: " + selected);
        }
    }//GEN-LAST:event_applyFilterBtnActionPerformed
    
    /**
     * Apply date-based filtering to appointments table.
     */
    private void applyDateFilter(String filterType) {
        try {
            java.util.List<Appointment> allAppointments = appointmentManager.getAllAppointments();
            java.time.LocalDate now = java.time.LocalDate.now();
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy");
            
            // Rebuild model with all appointments first
            appointmentModel = new AppointmentTableModel();
            
            for (Appointment apt : allAppointments) {
                try {
                    java.time.LocalDate aptDate = java.time.LocalDate.parse(apt.getDate(), formatter);
                    boolean include = false;
                    
                    switch (filterType) {
                        case "Today":
                            include = aptDate.equals(now);
                            break;
                        case "This Week":
                            include = !aptDate.isBefore(now) && !aptDate.isAfter(now.plusDays(7));
                            break;
                        case "All Upcoming":
                            include = !aptDate.isBefore(now);
                            break;
                        case "Past Appointments":
                            include = aptDate.isBefore(now);
                            break;
                    }
                    
                    if (include) {
                        appointmentModel.addAppointment(apt);
                    }
                } catch (Exception e) {
                    // Skip invalid dates
                }
            }
            
            appointmentsTable.setModel(appointmentModel);
        } catch (Exception e) {
            logger.severe("Error applying filter: " + e.getMessage());
        }
    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // Show the appointments view panel using CardLayout
        java.awt.CardLayout cl = (java.awt.CardLayout) appointmentsTab.getLayout();
        cl.show(appointmentsTab, "card6");  // card6 is the appointmentsView card
        logger.info("New appointment form cancelled");
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Opening billing modification panel...");
        logger.info("Billing modification opened");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Navigate to Appointments tab
        mainTabs.setSelectedIndex(1); // 1 = Appointments tab
        logger.info("Navigated to Appointments tab from home page");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Navigate to Appointments tab
        mainTabs.setSelectedIndex(1); // 1 = Appointments tab
        logger.info("Navigated to Appointments tab from home page");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Navigate to Appointments tab
        mainTabs.setSelectedIndex(1); // 1 = Appointments tab
        logger.info("Navigated to Appointments tab from home page");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selected = (String) jComboBox1.getSelectedItem();
        logger.info("Theme selected: " + selected);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String optionName = jTextField1.getText();
        String category = (String) jComboBox6.getSelectedItem();
        logger.info("Adding option: " + optionName + " to category: " + category);
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
    // ============ OBSERVER PATTERN IMPLEMENTATIONS ============
    
    @Override
    public void onFeaturesActivated(java.util.List<String> features) {
        for (String feature : features) {
            logger.info("Feature activated in UI: " + feature);
            // TODO: Update UI based on activated feature
        }
    }
    
    @Override
    public void onFeaturesDeactivated(java.util.List<String> features) {
        for (String feature : features) {
            logger.info("Feature deactivated in UI: " + feature);
            // TODO: Update UI based on deactivated feature
        }
    }
    
    @Override
    public void onInsuranceLevelChanged(FeatureManager.InsuranceLevel level) {
        logger.info("Insurance level changed to: " + level);
        updateProfileDisplay();
        // TODO: Update available appointment options based on insurance
    }
    
    @Override
    public void onPatientChanged(PatientManager.Patient patient) {
        logger.info("Patient changed");
        updateProfileDisplay();
    }
    
    @Override
    public void onPatientUpdated(PatientManager.Patient patient) {
        logger.info("Patient information updated");
        updateProfileDisplay();
    }
    
    @Override
    public void onAppointmentAdded(Appointment appointment) {
        logger.info("Appointment added: " + appointment.getDate());
        appointmentModel.addAppointment(appointment);
        updateHomePageAppointments();
    }
    
    @Override
    public void onAppointmentRemoved(Appointment appointment) {
        logger.info("Appointment removed");
        appointmentModel.removeAppointment(appointmentModel.getFilteredAppointmentCount() - 1);
        updateHomePageAppointments();
    }
    
    @Override
    public void onAppointmentUpdated(Appointment appointment) {
        logger.info("Appointment updated");
        appointmentModel.applyFilter(appointmentModel.getFilteredAppointmentCount() > 0 ? "" : "");
        updateHomePageAppointments();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminTab;
    private javax.swing.JLabel appointmentOpsLabel;
    private javax.swing.JButton applyFilterBtn;
    private javax.swing.JPanel appointmentsTab;
    private javax.swing.JTable appointmentsTable;
    private javax.swing.JScrollPane appointmentsTableScroll;
    private javax.swing.JPanel appointmentsView;
    private javax.swing.JButton bookBtn;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JButton cancelAppBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> consultationType;
    private com.toedter.calendar.JCalendar date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JPanel featurePanel;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JSeparator filterSeparator;
    private javax.swing.JPanel homeTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> location;
    private javax.swing.JTabbedPane mainTabs;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JButton newBtn;
    private javax.swing.JScrollPane notificationsRemindersList;
    private javax.swing.JComboBox<String> personnel;
    private javax.swing.JPanel profileTab;
    private javax.swing.JComboBox<String> roomType;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel settingsTab;
    private javax.swing.JList<String> timePeriodList;
    private javax.swing.JScrollPane upcomingAppointments;
    private javax.swing.JButton toggleAppointmentsBtn;
    // End of variables declaration//GEN-END:variables
}
