package View;

import Controller.SmartMedicalController;
import Model.TimeEventSystem;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.UUID;
import java.awt.event.ActionEvent;
import java.util.Date;
import java.util.List;

import Model.Appointment;

import java.time.LocalDate;

import Logger.Logger;

public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private final Logger appLogger = Logger.getInstance();
    private static SmartMedicalController controller = SmartMedicalController.getInstance();
    private static TimeEventSystem timeEventSystem = TimeEventSystem.getInstance();
    private java.util.List<Appointment> currentAppointments = new java.util.ArrayList<>();


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        try {

        } catch (Exception ignored) {
        }

        // populate appointments table from model
        refreshAppointmentsTable();
    }

    private void refreshAppointmentsTable() {
        try {
            List<Appointment> appts = controller.getFutureAppointments();
            currentAppointments = appts;
            String[] cols = new String[]{"Day", "Patient", "Status", "Result"};
            DefaultTableModel m = new DefaultTableModel(cols, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            for (Appointment a : appts) {
                String status = a.isCancelled() ? "Cancelled" : "Scheduled";
                m.addRow(new Object[]{a.getDate().toString(), a.getPatient(), status, a.getResult()});
            }
            appointmentsTable.setModel(m);
            appointmentsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception e) {
            logger.severe("refreshAppointmentsTable failed: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mainTabs = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        upcomingAppointments = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        appointment1 = new javax.swing.JPanel();
        date1 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        appointment2 = new javax.swing.JPanel();
        date2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        appointment3 = new javax.swing.JPanel();
        date3 = new javax.swing.JLabel();
        button3 = new javax.swing.JButton();
        notificationsRemindersList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        appointmentsTab = new javax.swing.JPanel();
        appointmentsView = new javax.swing.JPanel();
        appointmentsTableScroll = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        newBtn = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        modifyBtn = new javax.swing.JButton();
        cancelAppBtn = new javax.swing.JButton();
        applyFilterBtn = new javax.swing.JButton();
        timePeriodList = new javax.swing.JList<>();
        bookPanel = new javax.swing.JPanel();
        consultationType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        location = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        personnel = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        roomType = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JCalendar();
        bookBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        profileTab = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        settingsTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        featurePanel = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        notificationsTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Notifications & Reminders");

        jPanel2.setLayout(new java.awt.GridBagLayout());

        date1.setText("Thursday 05-06-2026");

        button1.setText("Modify/Cancel");
        button1.addActionListener(this::button1ActionPerformed);

        javax.swing.GroupLayout appointment1Layout = new javax.swing.GroupLayout(appointment1);
        appointment1.setLayout(appointment1Layout);
        appointment1Layout.setHorizontalGroup(
                appointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 751, Short.MAX_VALUE)
                        .addGroup(appointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(appointment1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                        .addGap(35, 35, 35)
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
        );
        appointment1Layout.setVerticalGroup(
                appointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(appointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(appointment1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(appointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                        .addGap(17, 17, 17)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 366;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        jPanel2.add(appointment1, gridBagConstraints);

        date2.setText("Thursday 05-06-2026");

        button2.setText("Modify/Cancel");
        button2.addActionListener(this::button2ActionPerformed);

        javax.swing.GroupLayout appointment2Layout = new javax.swing.GroupLayout(appointment2);
        appointment2.setLayout(appointment2Layout);
        appointment2Layout.setHorizontalGroup(
                appointment2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(appointment2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(appointment2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(date2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                                        .addGap(50, 50, 50)
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
        );
        appointment2Layout.setVerticalGroup(
                appointment2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(appointment2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(appointment2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(appointment2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                        .addGap(17, 17, 17)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 352;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 6);
        jPanel2.add(appointment2, gridBagConstraints);

        date3.setText("Thursday 05-06-2026");

        button3.setText("Modify/Cancel");
        button3.addActionListener(this::button3ActionPerformed);

        javax.swing.GroupLayout appointment3Layout = new javax.swing.GroupLayout(appointment3);
        appointment3.setLayout(appointment3Layout);
        appointment3Layout.setHorizontalGroup(
                appointment3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(appointment3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(appointment3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(date3, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                                        .addGap(50, 50, 50)
                                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
        );
        appointment3Layout.setVerticalGroup(
                appointment3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(appointment3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(appointment3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(appointment3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(date3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                        .addGap(17, 17, 17)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 352;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 41, 6);
        jPanel2.add(appointment3, gridBagConstraints);

        upcomingAppointments.setViewportView(jPanel2);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        notificationsRemindersList.setViewportView(jList1);

        jLabel6.setText("Upcoming appointment(s)");

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
                homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(upcomingAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                        .addGroup(homeTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(notificationsRemindersList)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(homeTabLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );
        homeTabLayout.setVerticalGroup(
                homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(homeTabLayout.createSequentialGroup()
                                .addContainerGap(238, Short.MAX_VALUE)
                                .addComponent(upcomingAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notificationsRemindersList, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(homeTabLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(709, Short.MAX_VALUE)))
        );

        mainTabs.addTab("Home", homeTab);

        appointmentsTab.setLayout(new java.awt.CardLayout());

        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {"22-12-2025", "Dr. Angst", "Hospital Dav", "Stomach pain", "Confirmed"},
                        {"06-01-25", "Dr. Stuckov", "Hospital Helen", "Vaccine", "Cancelled"}
                },
                new String[]{
                        "Date", "Doctor", "Location", "Reason", "Status"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        appointmentsTable.setColumnSelectionAllowed(true);
        appointmentsTableScroll.setViewportView(appointmentsTable);
        appointmentsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (appointmentsTable.getColumnModel().getColumnCount() > 0) {
            appointmentsTable.getColumnModel().getColumn(0).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(1).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(2).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(3).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        newBtn.setText("New Appointment");
        newBtn.addActionListener(this::newBtnActionPerformed);

        searchBar.setText("Search...");
        searchBar.setToolTipText("");
        searchBar.addActionListener(this::searchBarActionPerformed);

        modifyBtn.setText("Modify Appointment");
        modifyBtn.addActionListener(this::modifyBtnActionPerformed);

        cancelAppBtn.setText("Cancel Appointment");
        cancelAppBtn.addActionListener(this::cancelAppBtnActionPerformed);

        applyFilterBtn.setText("Apply Filter");
        applyFilterBtn.addActionListener(this::applyFilterBtnActionPerformed);

        timePeriodList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Today", "This Week", "All Upcoming", "Past Appointments"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });

        javax.swing.GroupLayout appointmentsViewLayout = new javax.swing.GroupLayout(appointmentsView);
        appointmentsView.setLayout(appointmentsViewLayout);
        appointmentsViewLayout.setHorizontalGroup(
                appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(appointmentsViewLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(modifyBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(newBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(applyFilterBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(searchBar)
                                        .addComponent(cancelAppBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(appointmentsViewLayout.createSequentialGroup()
                                                .addGap(0, 2, Short.MAX_VALUE)
                                                .addComponent(timePeriodList, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(appointmentsTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        appointmentsViewLayout.setVerticalGroup(
                appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(appointmentsViewLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(appointmentsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(appointmentsTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                                        .addGroup(appointmentsViewLayout.createSequentialGroup()
                                                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(timePeriodList, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(applyFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(modifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cancelAppBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );

        appointmentsTab.add(appointmentsView, "card6");

        consultationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Surgery", "Dentist", "Type1", "Type2", "Type3"}));
        consultationType.addActionListener(this::consultationTypeActionPerformed);

        jLabel7.setText("Consultation Type");

        jLabel8.setText("Location");

        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Hospital 1", "Hospital 2", "Hospital 3"}));
        location.addActionListener(this::locationActionPerformed);

        jLabel9.setText("Personnel");

        personnel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Doctor A", "Doctor B", "Doctor C"}));
        personnel.addActionListener(this::personnelActionPerformed);

        jLabel10.setText("Room Type");

        roomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Shared", "Private"}));
        roomType.addActionListener(this::roomTypeActionPerformed);

        bookBtn.setText("Cancel");
        bookBtn.addActionListener(this::bookBtnActionPerformed);

        cancelBtn.setText("Book");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
                bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bookPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(consultationType, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bookPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bookPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(personnel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bookPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bookBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        bookPanelLayout.setVerticalGroup(
                bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bookPanelLayout.createSequentialGroup()
                                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(consultationType)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(location)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(personnel)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(roomType)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        appointmentsTab.add(bookPanel, "card3");

        mainTabs.addTab("Appointments", appointmentsTab);

        jLabel12.setText("First Name : Abcdefg");

        jLabel13.setText("Last Name : Hijklmnop");

        jLabel14.setText("Sex : M");

        jLabel15.setText("Age : 31");

        jLabel16.setText("Ect : ...");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel16))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jLabel11.setText("Profile Image");

        jButton6.setText("Request Attestation");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Modify Billing");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel18.setText("Billing Information");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)
                                .addContainerGap(533, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                                        .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)
                                .addContainerGap(405, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(276, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout profileTabLayout = new javax.swing.GroupLayout(profileTab);
        profileTab.setLayout(profileTabLayout);
        profileTabLayout.setHorizontalGroup(
                profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profileTabLayout.createSequentialGroup()
                                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(profileTabLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileTabLayout.setVerticalGroup(
                profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profileTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                        .addGroup(profileTabLayout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        mainTabs.addTab("Profile", profileTab);

        featurePanel.setLayout(new java.awt.GridLayout(0, 1));

        jCheckBox5.setText("jCheckBox5");
        featurePanel.add(jCheckBox5);

        jCheckBox4.setText("jCheckBox4");
        featurePanel.add(jCheckBox4);

        jCheckBox1.setText("jCheckBox1");
        featurePanel.add(jCheckBox1);

        jCheckBox6.setText("jCheckBox6");
        featurePanel.add(jCheckBox6);

        jCheckBox3.setText("jCheckBox3");
        featurePanel.add(jCheckBox3);

        jScrollPane1.setViewportView(featurePanel);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel1.setText("Theme");

        jLabel3.setText("Option2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        jLabel4.setText("Option3");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        jLabel5.setText("Option4");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        jLabel17.setText("Option5");

        javax.swing.GroupLayout settingsTabLayout = new javax.swing.GroupLayout(settingsTab);
        settingsTab.setLayout(settingsTabLayout);
        settingsTabLayout.setHorizontalGroup(
                settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(settingsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(settingsTabLayout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(settingsTabLayout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(settingsTabLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(settingsTabLayout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(settingsTabLayout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(467, Short.MAX_VALUE))
        );
        settingsTabLayout.setVerticalGroup(
                settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(settingsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(settingsTabLayout.createSequentialGroup()
                                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox1)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox2)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox3)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox4)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox5)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 566, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        mainTabs.addTab("Settings", settingsTab);

        javax.swing.GroupLayout notificationsTabLayout = new javax.swing.GroupLayout(notificationsTab);
        notificationsTab.setLayout(notificationsTabLayout);
        notificationsTabLayout.setHorizontalGroup(
                notificationsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 795, Short.MAX_VALUE)
        );
        notificationsTabLayout.setVerticalGroup(
                notificationsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 736, Short.MAX_VALUE)
        );

        mainTabs.addTab("Notifications", notificationsTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainTabs)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainTabs.getAccessibleContext().setAccessibleName("mainTabs");

        pack();
    }// </editor-fold>

    private void searchBarActionPerformed(ActionEvent actionEvent) {
        // trigger filter/search when Enter pressed in search bar
        String filter = timePeriodList.getSelectedValue();
        String query = searchBar.getText();
        try {
            appLogger.log("View", "Search triggered: filter=" + filter + " query=" + query);
        } catch (Exception ignored) {
        }
        refreshAppointmentsTableFiltered(filter, query);
    }

    private void refreshAppointmentsTableFiltered(String filter, String query) {
        List<Appointment> appts;
        LocalDate currentDate = timeEventSystem.getCurrentDate();
        try {
            if (filter == null || filter.isEmpty() || filter.equals("All Upcoming")) {
                appts = controller.getFutureAppointments();
            } else if (filter.equals("Today")) {
                appts = new ArrayList<>();
                for (Appointment a : controller.getFutureAppointments()) {
                    LocalDate apptDate = a.getDate();
                    if (apptDate.isEqual(currentDate))
                        appts.add(a);
                }
            } else if (filter.equals("This Week")) {
                appts = new ArrayList<>();
                for (Appointment a : controller.getFutureAppointments()) {
                    LocalDate apptDate = a.getDate();
                    if (!apptDate.isBefore(currentDate) && !apptDate.isAfter(currentDate.plusDays(7)))
                        appts.add(a);
                }
            } else if (filter.equals("Past Appointments")) {
                appts = controller.getPastAppointments();
            } else {
                appts = controller.getFutureAppointments();
            }

            // apply text search if provided (search patient name)
            String q = (query == null) ? "" : query.trim().toLowerCase();
            String[] cols = new String[]{"Day", "Patient", "Status", "Result"};
            javax.swing.table.DefaultTableModel m = new javax.swing.table.DefaultTableModel(cols, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            // remember the list currently displayed so selection maps to ids
            currentAppointments = appts;
            for (Appointment a : appts) {
                if (!q.isEmpty() && !a.getPatient().toLowerCase().contains(q)) continue;
                String status = a.isCancelled() ? "Cancelled" : "Scheduled";
                m.addRow(new Object[]{"Day " + currentDate.toString() + " + " + (a.getDate().getDayOfMonth() - currentDate.getDayOfMonth()) + " (" + a.getDate().toString() + ")", a.getPatient(), status, a.getResult()});
            }
            appointmentsTable.setModel(m);
            appointmentsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception e) {
            logger.severe("refreshAppointmentsTableFiltered failed: " + e.getMessage());
        }
    }

    private void cancelAppointment() {
        int sel = appointmentsTable.getSelectedRow();
        try {
            appLogger.log("View", "button1 (modify/cancel) pressed, selectedRow=" + sel);
        } catch (Exception ignored) {
        }
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Select an appointment in the Appointments tab to modify/cancel.", "No selection", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        UUID id = null;
        if (sel < currentAppointments.size()) id = currentAppointments.get(sel).getId();
        if (id == null) {
            JOptionPane.showMessageDialog(this, "Unable to identify selected appointment.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean res = controller.cancelAppointmentById(id);
        if (res) {
            try {
                appLogger.log("View", "Appointment cancelled, row=" + sel);
            } catch (Exception ignored) {
            }
            JOptionPane.showMessageDialog(this, "Appointment cancelled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
            refreshAppointmentsTable();
        } else {
            try {
                appLogger.log("View", "Failed to cancel appointment, row=" + sel);
            } catch (Exception ignored) {
            }
            JOptionPane.showMessageDialog(this, "Failed to cancel appointment.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {
        cancelAppointment();
    }

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {
        cancelAppointment();
    }

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {
        cancelAppointment();
    }

    private void consultationTypeActionPerformed(java.awt.event.ActionEvent evt) {
        String sel = (String) consultationType.getSelectedItem();
        logger.info("Consultation type selected: " + sel);
    }

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {
        String sel = (String) location.getSelectedItem();
        logger.info("Location selected: " + sel);
    }

    private void personnelActionPerformed(java.awt.event.ActionEvent evt) {
        String sel = (String) personnel.getSelectedItem();
        logger.info("Personnel selected: " + sel);
    }

    private void roomTypeActionPerformed(java.awt.event.ActionEvent evt) {
        String sel = (String) roomType.getSelectedItem();
        logger.info("Room type selected: " + sel);
    }

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Date selected = date.getDate();
            if (selected == null) {
                JOptionPane.showMessageDialog(this, "Please select a date.", "No date", JOptionPane.WARNING_MESSAGE);
                return;
            }

            long diffMs = selected.getTime() - System.currentTimeMillis();
            int offsetDays = (int) Math.round(diffMs / 86400000.0);
            String patient = "UI_User"; // adapt to auth/user model when available
            String staff = "Dr. Stone";
            LocalDate day = timeEventSystem.getCurrentDate().plusDays(offsetDays);
            try {
                appLogger.log("View", "Book requested: patient=" + patient + " dateMs=" + selected.getTime() + " offsetDays=" + offsetDays + " day=" + day);
            } catch (Exception ignored) {}

            boolean ok = controller.addAppointmentDirect(patient, staff, day);
            if (ok) {
                try {
                    appLogger.log("View", "Book succeeded: patient=" + patient + " day=" + day);
                } catch (Exception ignored) {}

                JOptionPane.showMessageDialog(this, "Appointment requested for " + patient + " (day: " + day + ")", "Booked", JOptionPane.INFORMATION_MESSAGE);
                // refresh and go back to appointments view so user sees the new entry
                refreshAppointmentsTable();
                try {
                    bookPanel.setVisible(false);
                    appointmentsView.setVisible(true);
                    appointmentsTab.revalidate();
                    appointmentsTab.repaint();
                } catch (Exception ex) {
                    logger.severe("Failed to switch back to appointments view: " + ex.getMessage());
                }
            } else {
                try {
                    appLogger.log("View", "Book failed: patient=" + patient + " day=" + day);
                } catch (Exception ignored) {
                }
                JOptionPane.showMessageDialog(this, "Failed to add appointment.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            try {
                appLogger.log("View", "Book exception: " + e.getMessage());
            } catch (Exception ignored) {
            }
            JOptionPane.showMessageDialog(this, "Failed to book appointment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.severe("Book failed: " + e.getMessage());
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Request Attestation not implemented.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Show booking panel
        try {
            try {
                appLogger.log("View", "Open booking panel");
            } catch (Exception ignored) {
            }
            appointmentsView.setVisible(false);
            bookPanel.setVisible(true);
            appointmentsTab.revalidate();
            appointmentsTab.repaint();
        } catch (Exception e) {
            logger.severe("Failed to open booking panel: " + e.getMessage());
        }
    }

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int sel = appointmentsTable.getSelectedRow();
        try {
            appLogger.log("View", "Modify requested, selectedRow=" + sel);
        } catch (Exception ignored) {
        }
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Select an appointment to modify.", "No selection", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String input = JOptionPane.showInputDialog(this, "Enter new day (integer) to reschedule appointment:", "Reschedule", JOptionPane.PLAIN_MESSAGE);
        if (input == null) return; // cancelled
        try {
            int newDay = Integer.parseInt(input.trim());
            try {
                appLogger.log("View", "Reschedule requested: row=" + sel + " newDay=" + newDay);
            } catch (Exception ignored) {
            }
            UUID id = null;
            if (sel >= 0 && sel < currentAppointments.size()) id = currentAppointments.get(sel).getId();
            if (id == null) {
                JOptionPane.showMessageDialog(this, "Unable to identify selected appointment.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            LocalDate newDate = TimeEventSystem.getInstance().getCurrentDate().plusDays(newDay);
            boolean ok = controller.rescheduleAppointment(id, newDate);
            if (ok) {
                try {
                    appLogger.log("View", "Reschedule succeeded: row=" + sel + " newDay=" + newDay);
                } catch (Exception ignored) {
                }
                JOptionPane.showMessageDialog(this, "Appointment rescheduled to day " + newDay, "Rescheduled", JOptionPane.INFORMATION_MESSAGE);
                refreshAppointmentsTable();
            } else {
                try {
                    appLogger.log("View", "Reschedule failed: row=" + sel + " newDay=" + newDay);
                } catch (Exception ignored) {
                }
                JOptionPane.showMessageDialog(this, "Failed to reschedule appointment.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Invalid day value.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cancelAppBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int sel = appointmentsTable.getSelectedRow();
        try {
            appLogger.log("View", "Cancel requested via toolbar, selectedRow=" + sel);
        } catch (Exception ignored) {
        }
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Select an appointment to cancel.", "No selection", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        UUID id = null;
        if (sel >= 0 && sel < currentAppointments.size()) id = currentAppointments.get(sel).getId();
        if (id == null) {
            JOptionPane.showMessageDialog(this, "Unable to identify selected appointment.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean res = controller.cancelAppointmentById(id);
        if (res) {
            try {
                appLogger.log("View", "Cancel succeeded via toolbar, row=" + sel);
            } catch (Exception ignored) {
            }
            JOptionPane.showMessageDialog(this, "Appointment cancelled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
            refreshAppointmentsTable();
        } else {
            try {
                appLogger.log("View", "Cancel failed via toolbar, row=" + sel);
            } catch (Exception ignored) {
            }
            JOptionPane.showMessageDialog(this, "Failed to cancel appointment.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void applyFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String filter = timePeriodList.getSelectedValue();
        String query = searchBar.getText();
        try {
            appLogger.log("View", "Apply filter: " + filter + " query=" + query);
        } catch (Exception ignored) {
        }
        refreshAppointmentsTableFiltered(filter, query);
    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Back from booking panel to appointments view
        try {
            bookPanel.setVisible(false);
            appointmentsView.setVisible(true);
            appointmentsTab.revalidate();
            appointmentsTab.repaint();
        } catch (Exception e) {
            logger.severe("Failed to go back to appointments view: " + e.getMessage());
        }
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // Another back/close button behaviour: same as cancelBtn
        cancelBtnActionPerformed(evt);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton applyFilterBtn;
    private javax.swing.JPanel appointment1;
    private javax.swing.JPanel appointment2;
    private javax.swing.JPanel appointment3;
    private javax.swing.JPanel appointmentsTab;
    private javax.swing.JTable appointmentsTable;
    private javax.swing.JScrollPane appointmentsTableScroll;
    private javax.swing.JPanel appointmentsView;
    private javax.swing.JButton bookBtn;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton cancelAppBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> consultationType;
    private com.toedter.calendar.JCalendar date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JPanel featurePanel;
    private javax.swing.JPanel homeTab;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> location;
    private javax.swing.JTabbedPane mainTabs;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JButton newBtn;
    private javax.swing.JScrollPane notificationsRemindersList;
    private javax.swing.JPanel notificationsTab;
    private javax.swing.JComboBox<String> personnel;
    private javax.swing.JPanel profileTab;
    private javax.swing.JComboBox<String> roomType;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel settingsTab;
    private javax.swing.JList<String> timePeriodList;
    private javax.swing.JScrollPane upcomingAppointments;
    // End of variables declaration
}
